name: Delete Deployments

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Delete'     
        required: true
        default: 'tests'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v1.1.0
        with:
          token: ${{ github.token }}
          environment: ${{ github.event.inputs.environment }}
