name: Delete Deployments

on: [workflow_dispatch]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v1.1.0
        with:
          token: ${{ github.token }}
          environment: tests
